### ISSUE TITLE
Sending DNS record to DigitalOcean via API with WPCD Bash Script

### ISSUE THREAD

**Issue by SuperHondo** [WPCloudDeploy/wp-cloud-deploy#19]
What could be the best way to custom change in existing Bash Script and be able to send Website's IP address to DigitalOcean when Wordpress is installed on any given DO Droplet server. I tried but not able to achieve getting Server_IP from WPCD and be able to send it back to DigitalOcean via its API. Manually sending the DNS (A, CNAME etc) record via terminal is happening OK but want this in a automated way. I am trying to use it on the git repo so not able to get support on WPCD site. Thanks

**Comment by elindydotcom** [comment]
hmm....this feels like a support question which is not appropriate for this development repository.  Only software development code issues for the core plugin should be opened here (i.e.: bugs, code changes, pull requests etc.)

Please use either the private Facebook group or the support resources on the WPCD site for support otherwise.

**Comment by SuperHondo** [comment]
Hi sorry for the post, actually using the git repo for testing this plugin, so cannot access support group unless I make a purchase.

**Comment by angelmagico** [comment]
> 

Hello, I just added a post to the WPCD face group so that everyone can have this function since from what I see it is something very necessary.

Would you like to help make the code together?
