### ISSUE TITLE
OLS | PHP Error Log Location

### ISSUE THREAD

**Issue by unakriti** [WPCloudDeploy/wp-cloud-deploy#40]
Hi,

Thank you for this beta version.

I am testing compatibility of OLS stack with some plugins I use regularly including BPS Pro, a security plugin. 

Immediately after activating BPS Pro with a license key, the plugin sets up a few ini directives inside wp-config.php to define the error log path, and then it starts to throw up a WP dashboard message about error log location. Since I did not notice this issue earlier on Apache or even with WPCD's NGINX servers, I am pursuing the issue with the plugin author too.

Meanwhile, the OLS server does not see the FULL PATH to the error log location. So, on a fresh installation, I opened the httpd_config.conf file at /usr/local/lsws/conf/ and found this errorlog block

```
errorlog logs/error.log {
  logLevel                DEBUG
  debugLevel              0
  rollingSize             10M
  keepDays                35
  compressArchive         1
  enableStderrLog         1
} 
```
As you'd notice, it is not a full path (logs/error.log). 

On most OLS-specific documentation, I noticed this directive in a format such as **$SERVER_ROOT/logs/error.log** that resolves to a full path. So, my question is whether errorlog block (in httpd_config.conf file at /usr/local/lsws/conf/) needs a fix?

Kind regards,

**Comment by unakriti** [comment]
Thanks @osidney 

The file I an testing with is https://github.com/WPCloudDeploy/wp-cloud-deploy/archive/refs/heads/dev.zip

Kind regards,

**Comment by meramsey** [comment]
Hi,

I'm the one who has been primarily implementing the OLS related tweaks and happy to clear up the confusion.

The stuff in the vhost that looks like this
```
errorlog $VH_ROOT/html/logs/$VH_NAME.error_log {
  useServer               0
  logLevel                ERROR
  rollingSize             10M
  keepDays                35
  compressArchive         1
}
```

Specifically this block is the the equivalent of the Apache/Nginx Access/http error logs(think 500 errors) and so they are based on the Vhost/Server root path which can be explicit or just use vars as placeholders. This would be the only thing your site should be be trying to write too or use. Vhost level stuff is all setup to go to the specific Vhosts paths.  .
https://github.com/WPCloudDeploy/wp-cloud-deploy/blob/dev/includes/core/apps/wordpress-app/scripts/v1/raw/9999-common-functions.txt#L994-L1010

The fact the one for the Server level one doesn't have an explicit full path or a Var should not matter in that regard as its based off the Server root by default even if its not explicitly spelled out.  I suppose we could edit it to be more explicit but I'm not aware of reason why that would cause an error even for the Main server the way it is. So without more information Its hard to see what the cause of your issue is

In regards to the PHP error logs these are based on a Context and while you could explicitly put a full path there its not needed and this is also not something we wanted to nest in the server root level where clients would be unable to access their own unique logs.
https://github.com/WPCloudDeploy/wp-cloud-deploy/blob/dev/includes/core/apps/wordpress-app/scripts/v1/raw/9999-common-functions.txt#L1028-L1044

So this block is saying relative to your docroot html folder put the php error logs there.  There is nothing wrong with that either and it has worked for everything I have seen thrown at it including wordfence when configured correctly in their plugin.

Understandably it can be confusing as there are lots of directive blocks but the PHP Error log location based off the above writes to /var/www/DOMAIN/html/logs/php_error_log for each uniquely and is different from the $VH_NAME.error_log in the same folder which is for general http errors like openlitespeed errors 500 errors.

If your still having issues with something give us steps to reproduce the issue along with the exact versions of plugins and wordpress and settings so we can spin up a test site to see what is going on our end.


The way to test is to use a php file with an intentional and safe error or warning. Then visit that and check the php_error log gets created and entries logged.
this is a very basic one i used for testing.
https://github.com/meramsey/blaqpanel/blob/main/scripts/test/fatal-error.php

I have a few others in that folder for testing if needed
https://github.com/meramsey/blaqpanel/tree/main/scripts/test

**Comment by osidney** [comment]
> Oi
> 
> Sou eu quem tem implementado principalmente os ajustes relacionados ao OLS e feliz em esclarecer a confusão.
> 
> As coisas no vhost que se parece com isso
> 
> ```
> errorlog $VH_ROOT/html/logs/$VH_NAME.error_log {
>   useServer               0
>   logLevel                ERROR
>   rollingSize             10M
>   keepDays                35
>   compressArchive         1
> }
> ```
> 
> Especificamente, este bloco é o equivalente aos registros de erro Apache/Nginx Access/http (pense 500 erros) e, portanto, eles são baseados no caminho raiz Vhost/Server que pode ser explícito ou apenas usar vars como espaços reservados. Esta seria a única coisa que seu site deveria estar tentando escrever também ou usar. O material de nível Vhost é tudo configuração para ir para os caminhos vhosts específicos. . https://github.com/WPCloudDeploy/wp-cloud-deploy/blob/dev/includes/core/apps/wordpress-app/scripts/v1/raw/9999-common-functions.txt#L994-L1010
> 
> O fato de que o do nível do Servidor um não tem um caminho completo explícito ou um Var não deve importar a esse respeito como seu baseado fora da raiz do Servidor por padrão, mesmo que não esteja explicitamente escrito. Acho que poderíamos editá-lo para ser mais explícito, mas não estou ciente da razão pela qual isso causaria um erro mesmo para o servidor Principal do jeito que está. Então, sem mais informações É difícil ver qual é a causa do seu problema
> 
> Em relação aos registros de erro php estes são baseados em um contexto e, embora você possa explicitamente colocar um caminho completo lá não é necessário e isso também não é algo que queríamos aninhar no nível raiz do servidor onde os clientes não poderiam acessar seus próprios logs exclusivos. https://github.com/WPCloudDeploy/wp-cloud-deploy/blob/dev/includes/core/apps/wordpress-app/scripts/v1/raw/9999-common-functions.txt#L1028-L1044
> 
> Então este bloco está dizendo em relação à sua pasta docroot html coloque os registros de erro php lá. Não há nada de errado com isso também e funcionou para tudo o que vi jogado nele, incluindo wordfence quando configurado corretamente em seu plugin.
> 
> Compreensivelmente, pode ser confuso, pois há muitos blocos de diretiva, mas o local de registro de erro PHP baseado nas gravações acima para /var/www/DOMAIN/html/logs/php_error_log para cada um com exclusividade e é diferente do $VH_NAME.error_log na mesma pasta que é para erros gerais http, como erros de velocidade aberta 500 erros.
> 
> Se você ainda tiver problemas com algo, nos dê passos para reproduzir o problema junto com as versões exatas de plugins e wordpress e configurações para que possamos criar um local de teste para ver o que está acontecendo em nosso final.
> 
> A maneira de testar é usar um arquivo php com um erro intencional e seguro ou aviso. Em seguida, visite isso e verifique o registro de php_error é criado e as entradas registradas. este é um muito básico que eu usei para testes. https://github.com/meramsey/blaqpanel/blob/main/scripts/test/fatal-error.php
> 
> Tenho alguns outros na pasta para testes, se necessário https://github.com/meramsey/blaqpanel/tree/main/scripts/test

`errorlog $VH_ROOT/logs/$VH_NAME.error_log {
  useServer               0
  logLevel                ERROR
  rollingSize             10M
  keepDays                35
  compressArchive         1
}`
I do not welcome the error and access logs inside the html folder, for security and organizational reasons it should always be outside the WP files folder, otherwise I agree with you.

**Comment by meramsey** [comment]
To be clear the error logs are not directly inside the the html folder they are under a specific logs folder which is blocked from access at the vhost context level. So they are not public in any way. I can totally understand the cause for concern but unless the default configs were changed at the vhost level which is outside the control of the end user to intentionally break that there is no risk there.

That protection is hardcoded in by default into the vhost config for every site as you can see in the below code
https://github.com/WPCloudDeploy/wp-cloud-deploy/blob/dev/includes/core/apps/wordpress-app/scripts/v1/raw/9999-common-functions.txt#L1100-L1113
```
	context /logs/ {
	  location                logs/
	  allowBrowse             0
	  note                    Deny public access to logs directory

	  rewrite  {

	  }
	  addDefaultCharset       off

	  phpIniOverride  {

	  }
	}
```

If your not sure try visiting the log to confirm. It works very much in the same way the section above it works for specific files just for the logs folder as a whole.
https://github.com/WPCloudDeploy/wp-cloud-deploy/blob/dev/includes/core/apps/wordpress-app/scripts/v1/raw/9999-common-functions.txt#L1084-L1099
```
	# https://openlitespeed.org/kb/access-control/#Using_a_Context
	context exp:error_log|wp-config-sample.php|\.pl|\.cgi|\.lua|\.perl|\.sql|\.sh|wp-config.php|php.ini|\.log {
	  location                \$DOC_ROOT/\$0
	  allowBrowse             0
	  note                    Block access to scripts and files we don't want executed

	  rewrite  {

	  }
	  addDefaultCharset       off

	  phpIniOverride  {

	  }
	}
```

For more 'context' err um reference see their documentation: https://openlitespeed.org/kb/access-control/#Using_a_Context :)

**Comment by unakriti** [comment]
@meramsey Thank you for the explanation and it makes good sense.

The problem I am facing is with BPS Pro plugin. It tries to set a path to it's own php error log file inside wp-content folder but fails. I also tried to set the error logging via php.ini and .user.ini like this:
```
log_errors = On
error_log = /var/www/www.domain.com/html/wp-content/bps-backup/logs/bps_php_error.log
```
But, for some reason, even after a server restart, the plugin still does not detect the change. I should add, I have not faced this issue on Apache or NGINX.

BPS Pro plugin author had this to say about it:

```
Php.ini files and .user.ini files are directly related to a PHP server.  So there would not be any difference on Apache or OLS that have PHP servers.  But I know absolutely nothing about OLS. So something could be different.

BPS is getting the path from your server, which is the same on every type of web server.  So that would mean something else on OLS is telling BPS that that is the path to the php error log file.
```
I am going to trash the old server and retry all over again on a fresh box and, if its any different, share the result. Meanwhile, it'd be great you have any leads to troubleshoot this please? If you need, I can provide access (via email) to the test box.

Kind regards,

**Comment by unakriti** [comment]
Here's some more info please with screengrabs showing the steps I followed reproduced the error with on a fresh server with just the BPS Pro plugin (LS Cache deactivated) active:

**Default OLS Setup Result**

This first screeenshot is right after I setup BPS Pro. As you'd notice,
`PHP Error Log Location Set To: /var/www/www.domain.com/html/wp-content/bps-backup/logs/bps_php_error.log`

However, it seems like the errorlog block in the httpd_config.conf file at /usr/local/lsws/conf/ is setting this configuration below
`Error Log Path Seen by Server: logs/php_error_log`

At this stage, BPS Pro is logging PHP warnings into the file at logs/php_error_log

![WPCD OLS BPS Pro PHP Error Log Issue Screenshot from 2022-06-08 14-50-53](https://user-images.githubusercontent.com/58072649/172582731-754b9a58-9bca-45fc-ade8-68eeed2b591e.png)

**Manually Edited ErrorLog Block (Server Config)**

Next, I sFTP into the server and update the errorlog block in the httpd_config.conf file at /usr/local/lsws/conf/ to define a full path as /var/www/www.domain.com/html/wp-content/bps-backup/logs/bps_php_error.log and then I restart the OLS webserver from the WPCD server dashboard.I expected this to fix the problem, but no.

Here's a second screeshot from BPS Pro:
 
![WPCD OLS BPS Pro Error Logging Stage II Screenshot from 2022-06-08 15-07-47](https://user-images.githubusercontent.com/58072649/172585911-8818933b-1bdb-419f-96e2-d1dcc26e8428.png)

At this stage, 

- BPS Pro cannot write to the manually defined error log file and has stopped logging.
- OLS is logging everything (ALL) at /var/www/www.domain.com/html/wp-content/bps-backup/logs/bps_php_error.log

Not sure if I might be missing anything here or whether this is more of an issue with BPS Pro. Appreciate any advise please.

Kind regards,

**Comment by elindydotcom** [comment]
I'm not sure what bps pro is doing - that's not something we're familiar with and I don't fully understand everything you're doing or what the underlying issue is.   
 But two things to keep in mind:
1. Themes and plugins cannot override the log path defined by the server and site vhost configs.  
2. If you changed the server or site vhost config log path in the ols default log blocks then all logs will be sent to that new location you've defined.  Plugins will not be able to override that.

**Comment by unakriti** [comment]
Thanks @elindydotcom 

I not sure what's causing BPS Pro to behave differently - plays well with Apache and WPCD's NGINX servers, but on OLS, it displays dashboard warnings about the error log file. 

I'd make a note that it may not work without errors on WPCD's OLS server. 

Appreciate all commentators here.

Kind regards,

**Comment by Ed-AITpro** [comment]
BPS Pro is doing this standard check to get the location of the php error log file:  ini_get('error_log'). "ini_get — Gets the value of a configuration option". ini_get() will return the exact string stored in the php.ini file and NOT its int equivalent. If you have a PHP server then it comes with a default php.ini configuration file. BPS does not check any OLS server config files or Apache conf or vhost files or nginx conf files for the location of a php error log file. So if an OLS server config file needs to be changed in order to allow a PHP server php.ini file to do what it is designed to do then that would logically make sense. This section of the code in the OLS config file stands out to me as a likely section of the config code to change/modify to allow a custom php.ini file with error log directives in it to change the path to a custom php error log file:  phpIniOverride  {

**Comment by Ed-AITpro** [comment]
Going by this forum topic the phpinioverride section of code is used to set php directive values directly in the OLS config file instead of using the directives in the default php.ini file > https://community.cyberpanel.net/t/how-to-use-your-php-ini-for-each-domain/14915. So this is not the optimum approach/method. What would be the optimum method would be to create a custom php.ini file with the php error log directives in it to change the path to the default BPS php error log file. So if OLS does not allow custom php.ini files then that would be the first question to ask. ie "allow/create custom php.ini files on OLS".

**Comment by unakriti** [comment]
@Ed-AITpro 

Thank you for stopping by to explain how your plugin BPS Pro works in this particular context. Really appreciate it. 

@elindydotcom 
I sincerely hope this serves as a helpful input for further assessment and a potential resolution. 

Kind regards,

**Comment by elindydotcom** [comment]
Bringing this ticket back on track.

The original post that launched this whole thread was about how we were setting up the config for the error log.  The objection was that we were using relative paths instead of absolute paths.

So while this was legal and correct:
```
errorlog logs/error.log {
  logLevel                DEBUG
  debugLevel              0
  rollingSize             10M
  keepDays                35
  compressArchive         1
  enableStderrLog         1
} 
```
The general feedback was that we should use the full path.

So, the latest updates to the dev branch includes this request.  The configs will now look like this:

```
errorlog $SERVER_ROOT/logs/error.log {
  logLevel                DEBUG
  debugLevel              0
  rollingSize             10M
  keepDays                35
  compressArchive         1
  enableStderrLog         1
}
```
The effect is the same as it was before - no change in the behavior.
